server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/gn

security:
  auth_provider: keycloak  # can be keycloak or custom
  unauthorized:
    urls:
      - /swagger-ui/*
      - /v3/api-docs/**
  cors:
    allowed-origins: http://localhost:3000

springdoc:
  api-docs:
    enabled: true
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    doc-expansion: none
    disable-swagger-default-url: true

keycloak:
  client:
    admin:
     client_id: maps-by-server-side
     server_url: http://localhost:8083
     realm: gn
     username: admin
     password: admin
     client_secret: HOexqeeaaDDdZDS09kSSFokX5YEdCil2

validator:
  user:
    emailPattern: ^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
    passwordPattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$