server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/gn
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/gn
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: maps-by-server-side
            client-secret: JPP4erVY4XxqxM2Ycg4Em4NtyQTe2b4C
            scope: openid

security:
  auth_provider: keycloak  # can be keycloak or custom
  unauthorized:
    urls:
      - /swagger-ui/*
      - /v3/api-docs/**
  cors:
    allowed-origins: http://localhost:3000

springdoc:
  api-docs:
    enabled: true
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    doc-expansion: none
    disable-swagger-default-url: true

# 9AyJEXSjQw3mtADN1yD83WkbAMLotiRd // local secret
# nGojc659H0XaBif8VFftNJkVPtEhEYQD // server secret