server:
  port: ${SERVER_PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_HOST}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_SECRET}
            scope: ${KEYCLOAK_SCOPE}

security:
  auth_provider: keycloak  # can be keycloak or custom
  unauthorized:
    urls:
      - /swagger-ui/*
      - /v3/api-docs/**
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGIN}

springdoc:
  api-docs:
    enabled: true
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    doc-expansion: none
    disable-swagger-default-url: true


# 9AyJEXSjQw3mtADN1yD83WkbAMLotiRd // local secret
# nGojc659H0XaBif8VFftNJkVPtEhEYQD // server secret