server:
  port: ${SERVER_PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST}/realms/gn

security:
  auth_provider: keycloak  # can be keycloak or custom
  unauthorized:
    urls:
      - /swagger-ui/*
      - /v3/api-docs/**
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGIN}

springdoc:
  api-docs:
    enabled: true
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    doc-expansion: none
    disable-swagger-default-url: true

keycloak:
  client:
    admin:
      client_id: ${KEYCLOAK_CLIENT_ID}
      server_url: ${KEYCLOAK_HOST}
      realm: ${KEYCLOAK_REALM}
      username: ${KEYCLOAK_USERNAME}
      password: ${KEYCLOAK_PASSWORD}
      client_secret: ${KEYCLOAK_SECRET}

validator:
  user:
    emailPattern: ^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
    passwordPattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$

